worker_processes auto;
events {
    worker_connections 1024;
}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    upstream panel_backend { server 127.0.0.1:8080; }
    upstream xray_ws { server 127.0.0.1:18080; }
    upstream xray_xh { server 127.0.0.1:18081; }

    server {
        listen 8000;
        server_name _;

        # پروکسی XHTTP
        location /xh {
            proxy_pass http://xray_xh;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_buffering off;
        }

        # پروکسی WebSocket
        location /ws {
            proxy_pass http://xray_ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # پنل مدیریت و API (هر چیز دیگر)
        location / {
            proxy_pass http://panel_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}